---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: ckad-practice-observability
spec:
  title: CKAD Practice - Observability
  description: A port of the Observability section of Liptan Biswas' CKAD practice challenge
  vendor: kube.academy
  difficulty: beginner
  duration: 20m
  url: https://github.com/kube-academy/lab-ckad-observability
  content:
    files: github.com/kube-academy/lab-ckad-observability
  session:
    namespaces:
      security:
        policy: anyuid
      budget: medium
      secondary:
      - name: $(session_namespace)-apps
        budget: small
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: true
      examiner:
        enabled: true
