---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: coruscant
  name: coruscant
spec:
  containers:
  - name: coruscant
    image: busybox
    args:
    - sleep
    - infinity
  serviceAccountName: non-default-sa