#!/bin/bash

set -euo pipefail

kubectl get po tatooine -o jsonpath='{.spec.containers[0]}' | grep -q -w 'sleep'
kubectl get po tatooine -o jsonpath='{.status.containerStatuses[0].ready}' | grep -q -w 'true'
